coordinator:
  jvm:
    maxHeapSize: "2G"
    gcHelpers:
      enabled: false

worker:
  jvm:
    maxHeapSize: "2G"
    gcHelpers:
      enabled: false

server:
  workers: 2
  config:
    query:
      maxMemory: "4GB"

commonLabels: {}

tolerations:
  - key: "kubernetes.io/arch"
    operator: "Equal"
    value: "arm64"
    effect: "NoSchedule"

